spring.application.name=backend
spring.datasource.url=jdbc:mysql://localhost:3306/collabconnect?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Krish2006
spring.jpa.hibernate.ddl-auto=update
